stages:
  # - unit-testing
  - deploy
  - e2e-testing
    
variables:
  IMAGE_TAG: registry.gitlab.com/dhteam/playhouse-docker/sls-deploy:latest

####################################################
##                    TEMPLATES                   ##
####################################################
.deploy:
  stage: deploy
  image: $IMAGE_TAG
  before_script:
    - npm install --save-dev serverless-prune-plugin  
  script:
    - npm ci
    - sls deploy --stage $STAGE

.e2e-testing:
  stage: e2e-testing
  image: $IMAGE_TAG
  script:
    - npm ci
    - NODE_ENV=$STAGE npm run test:e2e

.deploy-docs:
  stage: deploy
  image: $IMAGE_TAG
  variables:
    UI_DIR: ui
  environment: gbl-prod
  script:
    - pip3 install awscli --upgrade
    - curl -Lo yaml2json https://github.com/wakeful/yaml2json/releases/latest/download/yaml2json-linux-amd64
    - chmod +x yaml2json
    - mv yaml2json /usr/local/bin/
    - npm ci
    - cp -r ./node_modules/@digitalhouse-dev/swagger-kit/src/$UI_DIR ./$UI_DIR
    - yaml2json ./swagger.yml >> ./$UI_DIR/swagger.json
    - aws s3 sync ./$UI_DIR s3://$SWAGGER_BUCKET_NAME/$STAGE/$API_NAME
    - aws cloudfront create-invalidation --distribution-id $SWAGGER_CDN_DISTRIBUTION_ID --paths "/$STAGE/$API_NAME/*"

####################################################
##                  GENERAL JOBS                  ##
####################################################
# unit-testing:
#   stage: unit-testing
#   tags:
#     - pg-qa-back
#   image: $IMAGE_TAG
#   script:
#     - npm ci
#     - npm test
#   only:
#     - merge_requests

####################################################
##                DEVELOPMENT JOBS                ##
####################################################
deploy-gbl-dev:
  extends:
    - .deploy
  tags:
    - pg-qa-back
  variables:
    STAGE: gbl-dev
  environment: gbl-dev
  only:
    - dev

deploy-docs-gbl-dev:
  extends:
    - .deploy-docs
  tags:
    - pg-qa-back
  variables:
    STAGE: gbl-dev
  only:
    - dev

e2e-testing-gbl-dev:
  extends:
    - .e2e-testing
  tags:
    - pg-qa-back
  variables:
    STAGE: gbl-dev
  only:
    - dev

####################################################
##                     QA JOBS                    ##
####################################################
deploy-gbl-qa:
  extends:
    - .deploy
  tags:
    - pg-qa-back
  variables:
    STAGE: gbl-qa
  environment: gbl-qa
  only:
    - QA

deploy-docs-gbl-qa:
  extends:
    - .deploy-docs
  tags:
    - pg-qa-back
  variables:
    STAGE: gbl-qa
  only:
    - QA

e2e-testing-gbl-qa:
  extends:
    - .e2e-testing
  tags:
    - pg-qa-back
  variables:
    STAGE: gbl-qa
  only:
    - QA

####################################################
##                 PRODUCTION JOBS                ##
####################################################
deploy-gbl-prod:
  extends:
    - .deploy
  tags:
    - pg-prod-back
  variables:
    STAGE: gbl-prod
  environment: gbl-prod
  only:
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/
  except:
    - branches

deploy-docs-gbl-prod:
  extends:
    - .deploy-docs
  tags:
    - pg-prod-back
  variables:
    STAGE: gbl-prod
  only:
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/
  except:
    - branches

e2e-testing-gbl-prod:
  extends:
    - .e2e-testing
  tags:
    - pg-prod-back
  variables:
    STAGE: gbl-prod
  only:
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/
  except:
    - branches
