image: node:16.17.0

stages:
  # - unit-testing
  - deploy
  - e2e-testing

####################################################
##                    TEMPLATES                   ##
####################################################
.deploy:
  stage: deploy
  before_script:
    - npm install -g serverless@3.21.0
    - npm install --save-dev serverless-plugin-datadog@5.4.0 serverless-offline@9.1.2
    - git clone https://$DATADOG_TEMPLATES:$DATADOG_TEMPLATES_TOKEN@gitlab.com/digitalhouse-team/do-sq/templates/serverless/datadog.git
  script:
    - npm ci
    - serverless deploy --verbose --stage $STAGE

.e2e-testing:
  stage: e2e-testing
  script:
    - npm ci
    - NODE_ENV=$STAGE npm run test:e2e

.deploy-docs:
  stage: deploy
  variables:
    UI_DIR: ui
  environment: prod
  script:
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install
    - curl -Lo yaml2json https://github.com/wakeful/yaml2json/releases/latest/download/yaml2json-linux-amd64
    - chmod +x yaml2json
    - mv yaml2json /usr/local/bin/
    - npm ci
    - cp -r ./node_modules/@digitalhouse-dev/swagger-kit/src/$UI_DIR ./$UI_DIR
    - yaml2json ./swagger.yml >> ./$UI_DIR/swagger.json
    - aws s3 sync ./$UI_DIR s3://$SWAGGER_BUCKET_NAME/$STAGE/$API_NAME
    - aws cloudfront create-invalidation --distribution-id $SWAGGER_CDN_DISTRIBUTION_ID --paths "/$STAGE/$API_NAME/*"

####################################################
##                  GENERAL JOBS                  ##
####################################################
# unit-testing:
#   stage: unit-testing
#   tags:
#     - pg-qa-back
#
#   script:
#     - npm ci
#     - npm test
#   only:
#     - merge_requests

####################################################
##                DEVELOPMENT JOBS                ##
####################################################

deploy-dev:
  extends:
    - .deploy
  tags:
    - pg-qa-back
  variables:
    STAGE: dev
  environment: dev
  only:
    - dev

deploy-docs-dev:
  extends:
    - .deploy-docs
  tags:
    - pg-qa-back
  variables:
    STAGE: dev
  only:
    - dev

e2e-testing-dev:
  extends:
    - .e2e-testing
  tags:
    - pg-qa-back
  variables:
    STAGE: dev
  only:
    - dev

####################################################
##                     QA JOBS                    ##
####################################################

deploy-qa:
  extends:
    - .deploy
  tags:
    - pg-qa-back
  variables:
    STAGE: qa
  environment: qa
  only:
    - qa

deploy-docs-qa:
  extends:
    - .deploy-docs
  tags:
    - pg-qa-back
  variables:
    STAGE: qa
  only:
    - qa

e2e-testing-qa:
  extends:
    - .e2e-testing
  tags:
    - pg-qa-back
  variables:
    STAGE: qa
  only:
    - qa

####################################################
##                 PRODUCTION JOBS                ##
####################################################

deploy-prod:
  extends:
    - .deploy
  tags:
    - pg-prod-back
  variables:
    STAGE: prod
  environment: prod
  only:
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/
  except:
    - branches

deploy-docs-prod:
  extends:
    - .deploy-docs
  tags:
    - pg-prod-back
  variables:
    STAGE: prod
  only:
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/
  except:
    - branches

e2e-testing-prod:
  extends:
    - .e2e-testing
  tags:
    - pg-prod-back
  variables:
    STAGE: prod
  only:
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/
  except:
    - branches
