stages:
  - build
  - deploy
  - e2e-testing
  
variables:
  IMAGE_TAG: registry.gitlab.com/dhteam/playhouse-docker/sls-deploy:latest

.deploy:
  stage: deploy
  tags:
    - pg-docker
  image: $IMAGE_TAG
  script:
    - npm ci
    - 'curl --header "PRIVATE-TOKEN: $API_TOKEN " "$ENVS_REPOSITORY/$STAGE_FOLDER%2Ftenant-api%2F%2Eenv%2E$STAGE%2Ejson/raw?ref=master" > .env.$STAGE.json'
    - sls deploy --stage $STAGE

# Templates
.e2e-testing:
  stage: e2e-testing
  tags:
    - pg-docker
  image: $IMAGE_TAG
  script:
      - npm ci
      - 'curl --header "PRIVATE-TOKEN: $API_TOKEN " "$ENVS_REPOSITORY/$STAGE_FOLDER%2Ftenant-api%2F%2Eenv%2Ee2e%2Ejson/raw?ref=master" > .env.e2e.json'
      - npm run test:e2e

# Development jobs
deploy-gbl-dev:
  extends:
    - .deploy
  variables:
    STAGE_FOLDER: dev
    STAGE: gbl-dev
  environment: gbl-dev
  only:
    refs:
      - dev

e2e-testing-gbl-dev:
  extends:
    - .e2e-testing
  variables:
    STAGE_FOLDER: dev
  only:
    refs:
      - dev

# QA jobs
deploy-gbl-qa:
  extends:
    - .deploy
  variables:
    STAGE_FOLDER: qa
    STAGE: gbl-qa
  environment: gbl-qa
  only:
    refs:
      - QA

e2e-testing-gbl-qa:
  extends:
    - .e2e-testing
  variables:
    STAGE_FOLDER: qa
  only:
    refs:
      - QA

# Prod jobs
deploy-gbl-prod:
  extends:
    - .deploy
  variables:
    STAGE_FOLDER: ar
    STAGE: gbl-prod
  environment: prod
  only:
    refs:
      - /^gbl-prod-.*$/
  except:
    - branches

e2e-testing-gbl-prod:
  extends:
    - .e2e-testing
  variables:
    STAGE_FOLDER: ar
  only:
    refs:
      - /^gbl-prod-.*$/
  except:
    - branches
