stages:
  # - unit-testing
  - deploy
  - e2e-testing
    
variables:
  IMAGE_TAG: registry.gitlab.com/dhteam/playhouse-docker/sls-deploy:latest

####################################################
##                    TEMPLATES                   ##
####################################################
.deploy:
  stage: deploy
  tags:
    - pg-docker
  image: $IMAGE_TAG
  script:
    - npm ci
    - sls deploy --stage $STAGE

.e2e-testing:
  stage: e2e-testing
  tags:
    - pg-docker
  image: $IMAGE_TAG
  script:
    - npm ci
    - NODE_ENV=$STAGE npm run test:e2e

####################################################
##                  GENERAL JOBS                  ##
####################################################
# unit-testing:
#   stage: unit-testing
#   tags:
#     - pg-docker
#   image: $IMAGE_TAG
#   script:
#     - npm ci
#     - npm test
#   only:
#     - merge_requests

####################################################
##                DEVELOPMENT JOBS                ##
####################################################
deploy-gbl-dev:
  extends:
    - .deploy
  variables:
    STAGE: gbl-dev
  environment: gbl-dev
  only:
    - dev

e2e-testing-gbl-dev:
  extends:
    - .e2e-testing
  variables:
    STAGE: gbl-dev
  only:
    - dev

####################################################
##                     QA JOBS                    ##
####################################################
deploy-gbl-qa:
  extends:
    - .deploy
  variables:
    STAGE: gbl-qa
  environment: gbl-qa
  only:
    - QA

e2e-testing-gbl-qa:
  extends:
    - .e2e-testing
  variables:
    STAGE: gbl-qa
  only:
    - QA

####################################################
##                 PRODUCTION JOBS                ##
####################################################
deploy-gbl-prod:
  extends:
    - .deploy
  variables:
    STAGE: gbl-prod
  environment: gbl-prod
  only:
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/
  except:
    - branches

e2e-testing-gbl-prod:
  extends:
    - .e2e-testing
  variables:
    STAGE: gbl-prod
  only:
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/
  except:
    - branches
