frameworkVersion: '3.21.0'

service: pg-tenant-api

params: ${file(./environment/params.yml)}

provider: ${file(./environment/provider.yml)}

plugins:
  - serverless-plugin-datadog
  - serverless-offline

custom:
  serverless-offline:
      host: 0.0.0.0
  cors: ${file(./environment/cors.yml)}
  datadog: ${file(./environment/datadog.yml)}

package:
  individually: true
  exclude:
      - '.*/**'

functions:
  get-by-id:
    description: Get by ID
    handler: src/tenants/get-by-id.handler
    events:
      - http:
          path: /{id}
          method: get
          cors: ${self:custom.cors}
         
  get-by-host:
    description: Get By Host
    handler: src/tenants/get-by-host.handler
    events:
      - http:
          path: /host/{name}
          method: get
          cors: ${self:custom.cors}
       
  get-strategies-by-host:
    description: Get strategies by host
    handler: src/tenants/get-strategies-by-host.handler
    events:
      - http:
          path: /host/{name}/strategies
          method: get
          cors: ${self:custom.cors}