service: pg-tenant-api

plugins:
  - serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0

package:
  individually: true
  exclude:
    - '.*/**'

provider:
  name: aws
  runtime: nodejs12.x
  environment: ${file(./env.${opt:stage, 'local'}.json)}

functions:
  get-by-name:
    handler: tenants/get-by-name.handler
    events:
      - http:
          path: /{name}
          method: get
          cors: true
  create:
    handler: tenants/create.handler
    events:
      - http:
          path: /
          method: post
          cors: true
  update:
    handler: tenants/update.handler
    events:
      - http:
          path: /{id}
          method: put
          cors: true