openapi: 3.0.0
servers:
  - description: Local Api
    url: 'http://playground-tenant-api.vm/local'
  - description: Development Api
    url: 'https://dev-pg-tenant-api.digitalhouse.com'
  - description: QA Api
    url: 'https://qa-pg-tenant-api.digitalhouse.com'
  - description: Prod Api
    url: 'https://prod-pg-tenant-api.digitalhouse.com'
info:
  version: 1.0.0
  title: Tenants
  contact:
    email: enzo@digitalhouse.com
paths:
  /:
    post:
      tags:
        - Tenants
      security:
        - ApiKeyAuth: []
      summary: Create a new tenant
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTenant'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/SuccessResponse'
                  - properties:
                      data:
                        $ref: '#/components/schemas/CreateTenant'
  /{id}:
    get:
      tags:
        - Tenants
      summary: Retrieve tenant info
      operationId: get-by-id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: uuidv4 del tenant
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/SuccessResponse'
                  - properties:
                      data:
                        $ref: '#/components/schemas/Tenant'
    put:
      tags:
        - Tenants
      security:
        - ApiKeyAuth: []
      summary: Update tenant info
      operationId: update
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTenant'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/SuccessResponse'
                  - properties:
                      data:
                        $ref: '#/components/schemas/UpdateTenant'
  /host/{name}:
    get:
      tags:
        - Tenants
      summary: Retrieve tenant info by hostname
      operationId: get-by-host
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
          description: Nombre del host perteneciente al cname
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/SuccessResponse'
                  - properties:
                      data:
                        $ref: '#/components/schemas/GetTenantByHostname'
  /host/{name}/strategies:
    get:
      tags:
        - Tenants
      summary: Retrieve tenant strategies by hostname
      operationId: get-strategies-by-host
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
          description: Nombre del host perteneciente al cname
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/SuccessResponse'
                  - properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/AuthStrategy'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas:
    TenantComunProperties:
      type: object
      properties:
        logoUrl:
          type: string
          description: Url del logo que se debe mostrar en el frontend
        lookandfeelUrl:
          type: string
          description: Url de las variables de css para el look&feel del tenant
        showPoweredBy:
          type: boolean
          description: Indica si se debe mostrar el footer con el powered by
        lang:
          type: string
          enum:
            - es-AR
            - pt-BR
          description: Indica el idioma con el que se debe mostrar el tenant
    Tenant:
      allOf:
        - $ref: '#/components/schemas/CreateTenant'
        - type: object
          properties:
            _id:
              type: string
    GetTenantByHostname:
      allOf:
        - $ref: '#/components/schemas/TenantComunProperties'
        - type: object
          properties:
            _id:
              type: string
            name:
              type: string
              description: Indica el nombre único del tenant
            country:
              type: string
              description: Indica el país root al que pertenece el host
            host:
              type: string
              description: Nombre canónico que será usado por el host
            authStrategies:
              type: array
              description: Indica la(s) estrategia(s) de autenticación permitidas para el host 
              items:
                $ref: '#/components/schemas/AuthStrategy'
    CreateTenant:
      allOf:
        - $ref: '#/components/schemas/TenantComunProperties'
        - type: object
          properties:
            name:
              type: string
              description: Indica el nombre único del tenant
            cnames:
              type: array
              items:
                $ref: '#/components/schemas/Cname'
    UpdateTenant:
      allOf:
        - $ref: '#/components/schemas/TenantComunProperties'
        - type: object
          properties:
            cnames:
              type: array
              items:
                $ref: '#/components/schemas/Cname'
    Cname:
      type: object
      properties:
        country:
          type: string
          description: Indica el país root al que pertenece el host
        host:
          type: string
          description: Nombre canónico que será usado por el host
        logoutUrl:
          type: string
          description: Sí existe, indica la url a la que se debe redireccionar al usuario al cerrar sesión
        authStrategies:
          type: array
          description: Indica la(s) estrategia(s) de autenticación permitidas para el host 
          items:
            $ref: '#/components/schemas/AuthStrategy'
    AuthStrategy:
      type: object
      properties:
        type:
          type: string
          enum:
            - OAuthStrategy
            - NativeAuthStrategy
        config:
          oneOf:
            - $ref: '#/components/schemas/OAuthStrategy'
            - $ref: '#/components/schemas/NativeAuthStrategy'
    OAuthStrategy:
      type: object
      properties:
        provider:
          type: string
          enum:
            - google
            - mercadolibre
          description: Indica el tipo de proveedor de OAuth
        providerUrl:
          type: string
          description: Indica la url del provider a la que se debe redireccionar
        buttonOnNativeLogin:
          type: boolean
          description: Indica si la estrategia pertenece a un botón del login nativo
        redirectOnOpen:
          type: boolean
          description: Indica si la estrategia debe redireccionar a otro login al abrir el tenant
        enablePublicSignUp:
          type: boolean
          description: Indica si la estrategia debe permitir registro de personas o sólo servirá para autenticación
        enablePublicEnrolment:
          type: boolean
          description: Indica si la estrategia debe permitir inscripción pública de personas
        clientId:
          type: string
          description: ID de cliente en el proveedor de oauth
        clientSecret:
          type: string
          description: Secret de cliente en el proveedor de oauth
        authorizationURL:
          type: string
          description: Url de autorización del proveedor de oauth
    NativeAuthStrategy:
      type: object
    SuccessResponse:
      type: object
      properties:
        code:
          type: number
        status:
          type: string
        message:
          type: string
