default:
  vertical: gbl
  service: pg-tenant-api
  process: playground
  project: pg
  dashboard: yhn-5y7-dqa
  #aws
  aws-bucket-name: gbl-core-serverless
  aws-bucket-kms-key: ${env:AWS_BUCKET_KMS_KEY, 'alias/aws/s3'}
  aws-lambda-kms-key-arn: ${env:AWS_LAMBDA_KMS_KEY, 'arn:aws:kms:us-east-1:999999999999:key/dummy'}
  aws-api-key-name: ${param:environment}-pg-tenant-api
  aws-tracing-apigateway: false
  aws-tracing-lambda: false
  aws-version-function: false
  aws-region: us-east-1
  aws-access-local: ''
  aws-secret-local: ''
  #datadog
  datadog-enabled: false
  datadog-log-level: error
  #sentry
  sentry-enabled: false
  sentry-dsn: ''
  #dynamo
  dynamo-table: ${param:environment}-${param:vertical}-pg-tenant
  dynamo-endpoint: ''
  #dax
  dax-endpoint: ${env:DAX_ENDPOINT, 'dummy'}
  #node
  node-env: ${param:environment}
prod:
  environment: prod
  #aws
  aws-log-retention: 30 
  aws-tracing-apigateway: true
  #datadog  
  datadog-enabled: true
  #sentry
  sentry-enabled: true
  sentry-dsn: 'https://f364e7ce5b164ea89e5c25a87b542d37@sentry.io/1547158'
qa:
  environment: qa
  #aws
  aws-log-retention: 7
  aws-tracing-apigateway: true
  #datadog  
  datadog-enabled: true
local:
  environment: local
  #aws
  aws-log-retention: 7
  aws-access-local: 'fake'
  aws-secret-local: 'fake'
  #dynamo
  dynamo-table: tenants
  dynamo-endpoint: http://pg-dynamodb:8000
  #dax
  dax-endpoint: ''
